FROM ubuntu:24.04 AS build
WORKDIR /app
ENV DOCKER=YES NODE_ENV=production
ADD . .

# apt install
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
        build-essential \
        autoconf \
        automake \
        cmake \
        libtool \
        libclang-dev  \
        libpcsclite-dev \
        libdvbv5-dev \
        libudev-dev \
        git \
        curl \
        ca-certificates \
        pkg-config

# cargo install
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain stable -y
ENV PATH="/root/.cargo/bin:${PATH}"

# libyakisoba
RUN git clone https://github.com/tsunoda14/libyakisoba.git && \
    cd libyakisoba && \
    autoreconf -i && \
    mkdir build && \
    cd build && \
    ../configure --sysconfdir /usr/local/etc && \
    make && \
    make install

# sobacas
RUN git clone https://github.com/tsunoda14/libsobacas.git   && \
    cd libsobacas  && \
    autoreconf -i  && \
    mkdir build  && \
    cd build  && \
    ../configure  && \
    make  && \
    make install

RUN git clone --recursive https://github.com/norikatsu/recisdb-rs.git && \
    cd recisdb-rs && \
    cargo build -F dvb --release

